In [ ]:
from ipaddress import ip_address
import pandas as pd
import numpy as np
import datetime as dt

from datetime import datetime, timedelta

from core.data import load_from_kaggle

/home/ulfgar/Lehrgänge/Projekte/portfolio/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
dataset_link = "nokkyu/deutsche-bahn-db-delays" # replace with your dataset link from Kaggle 
destination = "../data/raw"
dataset_name = dataset_link.split("/")[-1]

files = load_from_kaggle(
    dataset_link=dataset_link, 
    destination=destination,
    )

Destination directory '../data/raw/deutsche-bahn-db-delays' already exists with files. Skipping download (replace=False).

In [3]:
df = pd.read_csv("/".join(["../data/raw/", dataset_name, files[0]]))
df.head()

,ID,line,path,eva_nr,category,station,state,city,zip,long,lat,arrival_plan,departure_plan,arrival_change,departure_change,arrival_delay_m,departure_delay_m,info,arrival_delay_check,departure_delay_check
0,1573967790757085557-2407072312-14,20,Stolberg(Rheinl)Hbf Gl.44|Eschweiler-St.Jöris|...,8000001,2,Aachen Hbf,Nordrhein-Westfalen,Aachen,52064,6.091499,50.767800,2024-07-08 00:00:00,2024-07-08 00:01:00,2024-07-08 00:03:00,2024-07-08 00:04:00,3,3,NaN,on_time,on_time
1,349781417030375472-2407080017-1,18,NaN,8000001,2,Aachen Hbf,Nordrhein-Westfalen,Aachen,52064,6.091499,50.767800,NaN,2024-07-08 00:17:00,NaN,NaN,0,0,NaN,on_time,on_time
2,7157250219775883918-2407072120-25,1,Hamm(Westf)Hbf|Kamen|Kamen-Methler|Dortmund-Ku...,8000406,4,Aachen-Rothe Erde,Nordrhein-Westfalen,Aachen,52066,6.116475,50.770202,2024-07-08 00:03:00,2024-07-08 00:04:00,2024-07-08 00:03:00,2024-07-08 00:04:00,0,0,NaN,on_time,on_time
3,349781417030375472-2407080017-2,18,Aachen Hbf,8000404,5,Aachen West,Nordrhein-Westfalen,Aachen,52072,6.070715,50.780360,2024-07-08 00:20:00,2024-07-08 00:21:00,NaN,NaN,0,0,NaN,on_time,on_time
4,1983158592123451570-2407080010-3,33,Herzogenrath|Kohlscheid,8000404,5,Aachen West,Nordrhein-Westfalen,Aachen,52072,6.070715,50.780360,2024-07-08 00:20:00,2024-07-08 00:21:00,2024-07-08 00:20:00,2024-07-08 00:21:00,0,0,NaN,on_time,on_time

In [ ]:
#df.drop(
    labels=['id', 'line', 'eva_nr', 'state', 'zip', 'long', 'lat'], 
    axis=1, 
    inplace=True, 
    errors='ignore')

In [4]:
date_format = "%Y-%m-%d %H:%M:%S"
df["arrival_plan"] = pd.to_datetime(df["arrival_plan"], format=date_format)
df["departure_plan"] = pd.to_datetime(df["departure_plan"], format=date_format)
df["arrival_change"] = pd.to_datetime(df["arrival_change"], format=date_format)
df["departure_change"] = pd.to_datetime(df["departure_change"], format=date_format)

df["arrival_plan_time"] = df["arrival_plan"].dt.time
df["arrival_plan_date"] = df["arrival_plan"].dt.date

df["departure_plan_time"] = df["departure_plan"].dt.time
df["departure_plan_date"] = df["departure_plan"].dt.date

In [ ]:
df.head()

In [5]:
#'path' in 'path_list'
df['path_list'] = path_liste = df['path'].str.split('|')    
df.head()

,ID,line,path,eva_nr,category,station,state,city,zip,long,...,arrival_delay_m,departure_delay_m,info,arrival_delay_check,departure_delay_check,arrival_plan_time,arrival_plan_date,departure_plan_time,departure_plan_date,path_list
0,1573967790757085557-2407072312-14,20,Stolberg(Rheinl)Hbf Gl.44|Eschweiler-St.Jöris|...,8000001,2,Aachen Hbf,Nordrhein-Westfalen,Aachen,52064,6.091499,...,3,3,NaN,on_time,on_time,00:00:00,2024-07-08,00:01:00,2024-07-08,"[Stolberg(Rheinl)Hbf Gl.44, Eschweiler-St.Jöri..."
1,349781417030375472-2407080017-1,18,NaN,8000001,2,Aachen Hbf,Nordrhein-Westfalen,Aachen,52064,6.091499,...,0,0,NaN,on_time,on_time,NaT,NaT,00:17:00,2024-07-08,NaN
2,7157250219775883918-2407072120-25,1,Hamm(Westf)Hbf|Kamen|Kamen-Methler|Dortmund-Ku...,8000406,4,Aachen-Rothe Erde,Nordrhein-Westfalen,Aachen,52066,6.116475,...,0,0,NaN,on_time,on_time,00:03:00,2024-07-08,00:04:00,2024-07-08,"[Hamm(Westf)Hbf, Kamen, Kamen-Methler, Dortmun..."
3,349781417030375472-2407080017-2,18,Aachen Hbf,8000404,5,Aachen West,Nordrhein-Westfalen,Aachen,52072,6.070715,...,0,0,NaN,on_time,on_time,00:20:00,2024-07-08,00:21:00,2024-07-08,[Aachen Hbf]
4,1983158592123451570-2407080010-3,33,Herzogenrath|Kohlscheid,8000404,5,Aachen West,Nordrhein-Westfalen,Aachen,52072,6.070715,...,0,0,NaN,on_time,on_time,00:20:00,2024-07-08,00:21:00,2024-07-08,"[Herzogenrath, Kohlscheid]"

In [6]:
df['Start_Bahnhof'] = df['path_list'].str[0]

# 2. Die ersten Zeilen zur Überprüfung anzeigen
print("DataFrame mit neuer Spalte 'Start_Bahnhof':")
print(df[['path', 'path_list', 'Start_Bahnhof']].head())

DataFrame mit neuer Spalte 'Start_Bahnhof':
                                                path  \
0  Stolberg(Rheinl)Hbf Gl.44|Eschweiler-St.Jöris|...
1                                                NaN
2  Hamm(Westf)Hbf|Kamen|Kamen-Methler|Dortmund-Ku...
3                                         Aachen Hbf
4                            Herzogenrath|Kohlscheid

                                           path_list  \
0  [Stolberg(Rheinl)Hbf Gl.44, Eschweiler-St.Jöri...
1                                                NaN
2  [Hamm(Westf)Hbf, Kamen, Kamen-Methler, Dortmun...
3                                       [Aachen Hbf]
4                         [Herzogenrath, Kohlscheid]

               Start_Bahnhof
0  Stolberg(Rheinl)Hbf Gl.44
1                        NaN
2             Hamm(Westf)Hbf
3                 Aachen Hbf
4               Herzogenrath

In [ ]:
df.head()

In [7]:
# 1. Entferne Klammerzusätze (z.B. '(Rheinl)' oder '(Westf)')
# Der Ausdruck entfernt die Klammern inklusive Inhalt und angrenzender Leerzeichen.
df['Start_Bahnhof_clean'] = df['Start_Bahnhof'].str.replace(r'\s*\(.*?\)', '', regex=True)

# 2. Entferne Gleisangaben (z.B. ' Gl.44', ' Gl.8')
df['Start_Bahnhof_clean'] = df['Start_Bahnhof_clean'].str.replace(r'\sGl\.\d+', '', regex=True)

# Überprüfung des Ergebnisses:
print("Ergebnis der korrigierten Bereinigung:")
print(df[['Start_Bahnhof', 'Start_Bahnhof_clean']].head())

Ergebnis der korrigierten Bereinigung:
               Start_Bahnhof Start_Bahnhof_clean
0  Stolberg(Rheinl)Hbf Gl.44         StolbergHbf
1                        NaN                 NaN
2             Hamm(Westf)Hbf             HammHbf
3                 Aachen Hbf          Aachen Hbf
4               Herzogenrath        Herzogenrath

In [ ]:
df.head()

In [8]:
date_cols = ["arrival_plan", "departure_plan", "arrival_change", "departure_change"]
date_format = "%Y-%m-%d %H:%M:%S"

for col in date_cols:
    # Verwende errors='coerce', um ungültige Strings in NaT (Not a Time) umzuwandeln
    df[col] = pd.to_datetime(df[col], format=date_format, errors='coerce')

# Überprüfung des Datentyps
print("Datentypen nach erneuter Konvertierung:")
print(df[date_cols].dtypes)

Datentypen nach erneuter Konvertierung:
arrival_plan        datetime64[ns]
departure_plan      datetime64[ns]
arrival_change      datetime64[ns]
departure_change    datetime64[ns]
dtype: object

In [9]:
# 1. Basisdaten für die Erzeugung filtern: Züge, die irgendwo Leipzig enthalten könnten
leipzig_base = df[
    (df['station'].str.contains('Leipzig', na=False)) |
    (df['Start_Bahnhof_clean'].str.contains('Leipzig', na=False))
].copy()

# Falls die Basis leer ist oder zu klein, nehmen wir einfach die ersten Zeilen
if leipzig_base.shape[0] < 20:
    print(f"Basisdaten für Leipzig sind zu klein ({leipzig_base.shape[0]} Zeilen). Verwende die ersten 20 Zeilen des Haupt-DFs als Basis.")
    leipzig_base = df.head(20).copy()

# 2. 20 zufällige Zeilen auswählen und duplizieren
# Wir nehmen einfach die ersten 20 Zeilen der Basis für Reproduzierbarkeit
df_leipzig_verspaetung = leipzig_base.head(20).copy()

# 3. Manipulieren der Daten

# A) Setze Ankunfts-/Abfahrtsbahnhof auf 'Leipzig Hbf' (wenn nicht schon)
df_leipzig_verspaetung['station'] = 'Leipzig Hbf'
df_leipzig_verspaetung['station_clean'] = 'Leipzig Hbf' # Bereinigte Spalte aktualisieren

# B) Setze das Datum auf 2024-07-08 und generiere Verspätungen
sim_date = dt.datetime(2024, 7, 8)

for index in df_leipzig_verspaetung.index:
    # Generiere zufällige Verspätung zwischen 1 und 90 Minuten
    delay_min = np.random.randint(1, 91)
    
    # Der Plan-Zeitstempel muss das korrekte Datum 2024-07-08 erhalten.
    # Wir nehmen die Uhrzeit aus dem ursprünglichen Plan und setzen das Datum auf 2024-07-08
    
    # 1. Anpassung der Plan-Zeitstempel auf das Zieldatum
    if pd.notna(df_leipzig_verspaetung.loc[index, 'arrival_plan']):
        time_part = df_leipzig_verspaetung.loc[index, 'arrival_plan'].time()
        df_leipzig_verspaetung.loc[index, 'arrival_plan'] = dt.datetime.combine(sim_date.date(), time_part)
        
        # 2. Berechnung des geänderten Zeitstempels mit Verspätung
        df_leipzig_verspaetung.loc[index, 'arrival_change'] = df_leipzig_verspaetung.loc[index, 'arrival_plan'] + dt.timedelta(minutes=delay_min)
        df_leipzig_verspaetung.loc[index, 'arrival_delay_calc'] = delay_min
        df_leipzig_verspaetung.loc[index, 'arrival_delay_m'] = delay_min # Originalspalte mitschreiben
        df_leipzig_verspaetung.loc[index, 'arrival_delay_check'] = 'delayed' # Status anpassen

    if pd.notna(df_leipzig_verspaetung.loc[index, 'departure_plan']):
        time_part = df_leipzig_verspaetung.loc[index, 'departure_plan'].time()
        df_leipzig_verspaetung.loc[index, 'departure_plan'] = dt.datetime.combine(sim_date.date(), time_part)
        
        df_leipzig_verspaetung.loc[index, 'departure_change'] = df_leipzig_verspaetung.loc[index, 'departure_plan'] + dt.timedelta(minutes=delay_min)
        df_leipzig_verspaetung.loc[index, 'departure_delay_calc'] = delay_min
        df_leipzig_verspaetung.loc[index, 'departure_delay_m'] = delay_min
        df_leipzig_verspaetung.loc[index, 'departure_delay_check'] = 'delayed'


# Hinzufügen einer Spalte zur Identifizierung der fiktiven Daten
df_leipzig_verspaetung['synthetic'] = True

print(f"Es wurden {len(df_leipzig_verspaetung)} fiktive, verspätete Datensätze für 'Leipzig Hbf' erstellt.")
print("\nBeispiel der erzeugten Daten:")
print(df_leipzig_verspaetung[['arrival_plan', 'arrival_change', 'arrival_delay_calc', 'station_clean']].head())

Es wurden 20 fiktive, verspätete Datensätze für 'Leipzig Hbf' erstellt.

Beispiel der erzeugten Daten:
           arrival_plan      arrival_change  arrival_delay_calc station_clean
67  2024-07-08 00:30:00 2024-07-08 00:38:00                 8.0   Leipzig Hbf
152 2024-07-08 00:14:00 2024-07-08 01:10:00                56.0   Leipzig Hbf
159 2024-07-08 00:48:00 2024-07-08 02:15:00                87.0   Leipzig Hbf
160 2024-07-08 23:59:00 2024-07-09 00:43:00                44.0   Leipzig Hbf
805 2024-07-08 00:35:00 2024-07-08 01:47:00                72.0   Leipzig Hbf

In [ ]:
df_leipzig_verspaetung.head()

In [10]:
output_path = "../data/raw/df_leipzig_verspaetung_synthetic.csv"
df_leipzig_verspaetung.to_csv(output_path, index=False, sep=';', date_format=date_format)

print(f"\nFiktive Daten nach: {output_path} exportiert.")

Fiktive Daten nach: ../data/raw/df_leipzig_verspaetung_synthetic.csv exportiert.

In [11]:
# Hinzufügen der 'synthetic'-Spalte zum Original-DF mit False
df['synthetic'] = False

# Zusammenführen der DataFrames
df = pd.concat([df, df_leipzig_verspaetung], ignore_index=True)

print(f"\nDataFrames erfolgreich zusammengeführt. Neues Gesamt-DF hat {len(df)} Zeilen.")

DataFrames erfolgreich zusammengeführt. Neues Gesamt-DF hat 2061377 Zeilen.

In [ ]:
df.info()

#ab hier Neuland!!! Fragestellung 2 - 5, weiter ab # 1. Basisdaten für die Erzeugung filtern:

In [13]:
# 1. Filtern der Daten
leipzig_hbf_delays = df[
    (df['station_clean'] == 'Leipzig Hbf') &  # Filter auf Leipzig Hbf
    (df['arrival_plan'].dt.date == pd.to_datetime('2024-07-08').date()) & # Filter auf das Zieldatum
    (df['arrival_delay_calc'] > 0) # Nur Züge mit Verspätung anzeigen
].copy()

# 2. Auswahl der relevanten Spalten und Sortierung
leipzig_hbf_delays_sorted = leipzig_hbf_delays.sort_values(
    by='arrival_delay_calc', 
    ascending=False
)[['arrival_plan', 'arrival_change', 'arrival_delay_calc', 'line', 'synthetic']].reset_index(drop=True)

# Umbenennen für bessere Lesbarkeit
leipzig_hbf_delays_sorted.columns = [
    'Ankunft (Plan)', 
    'Ankunft (Geändert)', 
    'Verspätung (Min)', 
    'Zug-ID', 
    'Synthetisch'
]

In [14]:
leipzig_hbf_delays_sorted.head()

,Ankunft (Plan),Ankunft (Geändert),Verspätung (Min),Zug-ID,Synthetisch
0,2024-07-08 00:48:00,2024-07-08 02:15:00,87.0,113,True
1,2024-07-08 00:40:00,2024-07-08 02:07:00,87.0,4,True
2,2024-07-08 00:14:00,2024-07-08 01:36:00,82.0,22,True
3,2024-07-08 00:47:00,2024-07-08 02:08:00,81.0,6,True
4,2024-07-08 00:19:00,2024-07-08 01:40:00,81.0,20,True

In [15]:
# 1. Basisdaten für die Erzeugung filtern: Züge, die irgendwo Leipzig enthalten könnten
# Wir benötigen hierfür die Bibliotheken numpy (np), pandas (pd), datetime (dt) und timedelta.
# Stellen Sie sicher, dass diese oben im Skript importiert sind.

# Filter auf alle Zeilen, die "Leipzig" in der Zielstation oder der bereinigten Startstation enthalten
leipzig_base = df[
    (df['station'].str.contains('Leipzig', na=False)) |
    (df['Start_Bahnhof_clean'].str.contains('Leipzig', na=False))
].copy()

# Falls die Basis leer ist oder zu klein, nehmen wir einfach die ersten Zeilen
if leipzig_base.shape[0] < 50:
    print(f"Basisdaten für Leipzig sind zu klein ({leipzig_base.shape[0]} Zeilen). Verwende die vorhandenen Zeilen und ziehe Stichproben mit Ersetzung.")
    # Erzeuge 50 Zeilen, nutze replace=True, um Duplikate zu erlauben
    df_leipzig_verspaetung = leipzig_base.sample(n=50, replace=True, random_state=42).copy()
else:
    # Wenn genug Daten existieren, ziehe 50 zufällige Zeilen ohne Ersetzung
    df_leipzig_verspaetung = leipzig_base.sample(n=50, replace=False, random_state=42).copy()

print(f"Es werden {len(df_leipzig_verspaetung)} Basiszeilen zur Manipulation verwendet.")

# 2. Manipulieren der Daten
df_leipzig_verspaetung['station'] = 'Leipzig Hbf'
df_leipzig_verspaetung['station_clean'] = 'Leipzig Hbf' # Bereinigte Spalte aktualisieren
df_leipzig_verspaetung['city'] = 'Leipzig'
df_leipzig_verspaetung['state'] = 'Sachsen'

# Setze das Datum auf 2024-07-08 und generiere Verspätungen
sim_date = dt.datetime(2024, 7, 8)
date_format = "%Y-%m-%d %H:%M:%S" # Für den Export

for index in df_leipzig_verspaetung.index:
    # Generiere zufällige Verspätung zwischen 1 und 90 Minuten
    delay_min = np.random.randint(1, 91)
    
    # Der Plan-Zeitstempel muss das korrekte Datum 2024-07-08 erhalten.
    # WICHTIG: Prüfen auf NaT, da die Konvertierung fehlerhaft war
    
    # Ankunft manipulieren
    if pd.notna(df_leipzig_verspaetung.loc[index, 'arrival_plan']):
        time_part = df_leipzig_verspaetung.loc[index, 'arrival_plan'].time()
        df_leipzig_verspaetung.loc[index, 'arrival_plan'] = dt.datetime.combine(sim_date.date(), time_part)
        
        df_leipzig_verspaetung.loc[index, 'arrival_change'] = df_leipzig_verspaetung.loc[index, 'arrival_plan'] + dt.timedelta(minutes=delay_min)
        df_leipzig_verspaetung.loc[index, 'arrival_delay_calc'] = delay_min
        df_leipzig_verspaetung.loc[index, 'arrival_delay_m'] = delay_min 
        df_leipzig_verspaetung.loc[index, 'arrival_delay_check'] = 'delayed' 
    else:
        # Falls kein Ankunftsplan vorhanden (durch NaT oder NaN), leeren wir auch die Delay-Werte
        df_leipzig_verspaetung.loc[index, ['arrival_delay_calc', 'arrival_delay_m']] = np.nan


    # Abfahrt manipulieren (falls es sich um eine Durchfahrt/Start handelt)
    if pd.notna(df_leipzig_verspaetung.loc[index, 'departure_plan']):
        time_part = df_leipzig_verspaetung.loc[index, 'departure_plan'].time()
        df_leipzig_verspaetung.loc[index, 'departure_plan'] = dt.datetime.combine(sim_date.date(), time_part)
        
        df_leipzig_verspaetung.loc[index, 'departure_change'] = df_leipzig_verspaetung.loc[index, 'departure_plan'] + dt.timedelta(minutes=delay_min)
        df_leipzig_verspaetung.loc[index, 'departure_delay_calc'] = delay_min
        df_leipzig_verspaetung.loc[index, 'departure_delay_m'] = delay_min
        df_leipzig_verspaetung.loc[index, 'departure_delay_check'] = 'delayed'
    else:
        df_leipzig_verspaetung.loc[index, ['departure_delay_calc', 'departure_delay_m']] = np.nan


# Hinzufügen einer Spalte zur Identifizierung der fiktiven Daten
df_leipzig_verspaetung['synthetic'] = True

print(f"Es wurden {len(df_leipzig_verspaetung)} fiktive, verspätete Datensätze für 'Leipzig Hbf' erstellt.")

# 3. Export der fiktiven Daten
output_path = "../data/raw/df_leipzig_verspaetung_synthetic_50.csv"
df_leipzig_verspaetung.to_csv(output_path, index=False, sep=';', date_format=date_format)
print(f"Fiktive Daten nach: {output_path} exportiert.")

# 4. DataFrames zusammenführen (Wiederholung, da wir df_leipzig_verspaetung neu erstellt haben)
# Hinzufügen der 'synthetic'-Spalte zum Original-DF mit False, falls noch nicht geschehen
if 'synthetic' not in df.columns:
    df['synthetic'] = False

# Entfernen alter Leipzig-Simulationsdaten (falls vorhanden), um keine Duplikate zu erzeugen
df = df[df['synthetic'] == False].copy()

# Zusammenführen der DataFrames
df = pd.concat([df, df_leipzig_verspaetung], ignore_index=True)
print(f"DataFrames erfolgreich zusammengeführt. Neues Gesamt-DF hat {len(df)} Zeilen.")

Es werden 50 Basiszeilen zur Manipulation verwendet.
Es wurden 50 fiktive, verspätete Datensätze für 'Leipzig Hbf' erstellt.
Fiktive Daten nach: ../data/raw/df_leipzig_verspaetung_synthetic_50.csv exportiert.
DataFrames erfolgreich zusammengeführt. Neues Gesamt-DF hat 2061407 Zeilen.

In [ ]:
df.head()

In [16]:
# 1. Verspätete Züge (synthetische Ankünfte in Leipzig Hbf)
df_leipzig_synthetic = df[
    (df['station_clean'] == 'Leipzig Hbf') &
    (df['synthetic'] == True) &
    (df['arrival_delay_calc'].notna())
].copy()

# 2. Potentielle Anschlüsse (reale Abfahrten von Leipzig Hbf)
# Wir verwenden nur NICHT-synthetische Daten für die Anschlusssuche
df_leipzig_departures = df[
    (df['Start_Bahnhof_clean'] == 'Leipzig Hbf') &
    (df['departure_plan'].dt.date == pd.to_datetime('2024-07-08').date()) &
    (df['synthetic'] == False) 
].copy()

print(f"Basis für Anschlüsse: {len(df_leipzig_departures)} reale Abfahrten am 2024-07-08.")

Basis für Anschlüsse: 1052 reale Abfahrten am 2024-07-08.

In [17]:
def find_next_connection(delayed_trains_df, departure_trains_df, min_transfer_minutes=5):
    """
    Findet für jeden verspäteten Zug den nächstmöglichen Anschlusszug (planmäßige Abfahrt).
    """
    connection_results = []
    min_transfer_time = pd.Timedelta(minutes=min_transfer_minutes)

    # Sortiere alle potenziellen Anschlüsse nach planmäßiger Abfahrtszeit
    departure_trains_df = departure_trains_df.sort_values(by='departure_plan').reset_index(drop=True)

    # Iteriere durch jeden verspäteten Ankunftszug
    for index, arr_row in delayed_trains_df.iterrows():
        arrival_changed = arr_row['arrival_change']
        earliest_departure_plan = arrival_changed + min_transfer_time

        # Suche den ersten Zug, dessen planmäßige Abfahrt >= der frühestmöglichen Abfahrtszeit ist
        next_connection_candidates = departure_trains_df[
            departure_trains_df['departure_plan'] >= earliest_departure_plan
        ]
        
        # Prüfung, ob ein Anschluss gefunden wurde
        if not next_connection_candidates.empty:
            conn_row = next_connection_candidates.iloc[0]
            
            # Wartezeit berechnen (Zeit zwischen tatsächlicher Ankunft und planmäßiger Abfahrt des Anschlusses)
            wait_time = conn_row['departure_plan'] - arrival_changed
            
            # Zielbahnhof extrahieren (letzter Halt in der path_list oder die Zielstation selbst)
            final_destination = conn_row['path_list'][-1] if isinstance(conn_row['path_list'], list) and conn_row['path_list'] else conn_row['station']

            connection_results.append({
                'Delay_Ankunft_Geändert': arrival_changed,
                'Delay_Min': arr_row['arrival_delay_calc'],
                'Delay_Kategorie': arr_row['category'],
                
                'Anschluss_Kategorie': conn_row['category'],
                'Anschluss_Zielbahnhof': final_destination,
                'Verpasste_Verbindung': (conn_row['departure_plan'] - arr_row['arrival_plan']).total_seconds() / 60 < min_transfer_minutes,
                'Naechste_Abfahrt': conn_row['departure_plan'],
                'Wartezeit_Min': wait_time.total_seconds() / 60
            })

    return pd.DataFrame(connection_results)

# Ausführung der Analyse
connection_analysis_df = find_next_connection(df_leipzig_synthetic, df_leipzig_departures)

In [18]:
connection_analysis_df.head()

,Delay_Ankunft_Geändert,Delay_Min,Delay_Kategorie,Anschluss_Kategorie,Anschluss_Zielbahnhof,Verpasste_Verbindung,Naechste_Abfahrt,Wartezeit_Min
0,2024-07-08 13:38:00,55.0,5,5,Leipzig-Sellerhausen,False,2024-07-08 13:43:00,5.0
1,2024-07-08 17:27:00,7.0,4,5,Bitterfeld,False,2024-07-08 17:33:00,6.0
2,2024-07-08 20:10:00,78.0,4,5,Leipzig-Paunsdorf,False,2024-07-08 20:15:00,5.0
3,2024-07-08 11:00:00,2.0,5,5,Leipzig Hbf,False,2024-07-08 11:05:00,5.0
4,2024-07-08 16:00:00,16.0,4,5,Leipzig MDR,False,2024-07-08 16:05:00,5.0

In [20]:
# Berechnung der Wartezeit-Statistiken
waiting_time_stats = connection_analysis_df['Wartezeit_Min'].describe()

# Aufteilung der Wartezeiten nach Zugkategorie (ICE/IC vs. RE/RB) des Anschlusszuges
# Wir gruppieren nach der Kategorie des Anschlusszuges
waiting_time_by_category = connection_analysis_df.groupby('Anschluss_Kategorie')['Wartezeit_Min'].agg(['mean', 'max', 'count'])

print("### Statistiken zur Wartezeit am Leipzig Hbf (50 simulierte Verspätungen) 📈")

print("\n--- 1. Gesamte Wartezeit-Verteilung (Minuten) ---")
print(waiting_time_stats.to_frame())

print("\n--- 2. Durchschnittliche und maximale Wartezeit nach Anschluss-Kategorie ---")
print(waiting_time_by_category)

### Statistiken zur Wartezeit am Leipzig Hbf (50 simulierte Verspätungen) 📈

--- 1. Gesamte Wartezeit-Verteilung (Minuten) ---
       Wartezeit_Min
count      40.000000
mean        8.175000
std        15.425399
min         5.000000
25%         5.000000
50%         5.000000
75%         6.000000
max       103.000000

--- 2. Durchschnittliche und maximale Wartezeit nach Anschluss-Kategorie ---
                          mean    max  count
Anschluss_Kategorie
1                     6.000000    6.0      1
2                     6.000000    6.0      1
3                    24.800000  103.0      5
4                     5.875000    8.0     16
5                     5.705882   11.0     17

In [21]:
def analyze_missed_and_next_connections(delayed_trains_df, departure_trains_df, min_transfer_minutes=5):
    """
    Findet für jeden verspäteten Zug den verpassten Anschluss (falls vorhanden) und den nächsten Anschluss.
    """
    results = []
    min_transfer_time = pd.Timedelta(minutes=min_transfer_minutes)
    
    # Sortiere Abfahrten einmalig nach Planzeit
    departure_trains_df = departure_trains_df.sort_values(by='departure_plan').reset_index(drop=True)

    for index, arr_row in delayed_trains_df.iterrows():
        arr_plan = arr_row['arrival_plan']
        arr_changed = arr_row['arrival_change']
        
        # 1. Bestimme den letzten potenziell erreichbaren Zug (Z_verpasst)
        # Planmäßige Abfahrt liegt nach planmäßiger Ankunft + Mindestumstiegszeit
        # UND planmäßige Abfahrt liegt vor tatsächlicher Ankunft + Mindestumstiegszeit
        
        # Züge, die planmäßig erreichbar waren
        potentially_reachable = departure_trains_df[
            departure_trains_df['departure_plan'] >= arr_plan + min_transfer_time
        ]

        # Züge, die tatsächlich verpasst wurden (Abfahrt vor tatsächlicher Ankunft + Puffer)
        missed_candidates = potentially_reachable[
            potentially_reachable['departure_plan'] < arr_changed + min_transfer_time
        ]
        
        # 2. Bestimme den nächstmöglichen Zug (Z_next)
        earliest_departure_plan = arr_changed + min_transfer_time
        next_candidates = departure_trains_df[
            departure_trains_df['departure_plan'] >= earliest_departure_plan
        ]

        missed_conn = missed_candidates.iloc[-1] if not missed_candidates.empty else None
        next_conn = next_candidates.iloc[0] if not next_candidates.empty else None
        
        # Extrahiere Daten für den verpassten Zug
        missed_data = {
            'Verpasst_ID': missed_conn['line'] if missed_conn is not None else np.nan,
            'Verpasst_Kat': missed_conn['category'] if missed_conn is not None else 'Kein direkter Anschluss verpasst',
            'Verpasst_Ziel': missed_conn['path_list'][-1] if missed_conn is not None and isinstance(missed_conn['path_list'], list) else (missed_conn['station'] if missed_conn is not None else np.nan),
            'Verpasst_Abfahrt_Plan': missed_conn['departure_plan'] if missed_conn is not None else pd.NaT,
        }
        
        # Extrahiere Daten für den nächsten Zug und berechne Wartezeit
        next_data = {
            'Naechste_Abfahrt': next_conn['departure_plan'] if next_conn is not None else pd.NaT,
            'Naechste_Wartezeit_Min': ((next_conn['departure_plan'] - arr_changed).total_seconds() / 60) if next_conn is not None else np.nan,
        }

        results.append({
            'Verspätung_Min': arr_row['arrival_delay_calc'],
            'Verspätung_Kat': arr_row['category'],
            **missed_data,
            **next_data
        })

    return pd.DataFrame(results)

# Führen Sie die erweiterte Analyse aus
missed_connections_df = analyze_missed_and_next_connections(df_leipzig_synthetic, df_leipzig_departures)

In [22]:
missed_connections_df.head()

,Verspätung_Min,Verspätung_Kat,Verpasst_ID,Verpasst_Kat,Verpasst_Ziel,Verpasst_Abfahrt_Plan,Naechste_Abfahrt,Naechste_Wartezeit_Min
0,55.0,5,110,5,Großsteinberg,2024-07-08 13:41:00,2024-07-08 13:43:00,5.0
1,7.0,4,13,5,Königsborn,2024-07-08 17:31:00,2024-07-08 17:33:00,6.0
2,78.0,4,20,4,Leipzig Hbf,2024-07-08 20:14:00,2024-07-08 20:15:00,5.0
3,60.0,5,10,5,Eilenburg,2024-07-08 23:55:00,NaT,NaN
4,2.0,5,22,5,Gera Hbf,2024-07-08 11:04:00,2024-07-08 11:05:00,5.0

In [23]:
# Sortierung nach der längsten Wartezeit
missed_connections_df_sorted = missed_connections_df.sort_values(
    by='Naechste_Wartezeit_Min', 
    ascending=False
).reset_index(drop=True)

# Auswahl und Umbenennung für die Darstellung
final_missed_output = missed_connections_df_sorted[[
    'Verspätung_Min', 
    'Verspätung_Kat', 
    'Verpasst_Kat', 
    'Verpasst_Ziel', 
    'Verpasst_Abfahrt_Plan', 
    'Naechste_Abfahrt', 
    'Naechste_Wartezeit_Min'
]].head(10)

final_missed_output.columns = [
    'Verspätung (Min)', 
    'Kat. (Ankunft)', 
    'Kat. (Verpasst)', 
    'Ziel (Verpasst)', 
    'Abfahrt (Verpasst Plan)', 
    'Abfahrt (Nächste Plan)', 
    'Wartezeit (Min)'
]

print("### Top 10 Verpasste Anschlüsse und Wartezeiten in Leipzig Hbf 💔")
print(final_missed_output)

### Top 10 Verpasste Anschlüsse und Wartezeiten in Leipzig Hbf 💔
   Verspätung (Min)  Kat. (Ankunft)                   Kat. (Verpasst)  \
0              65.0               3  Kein direkter Anschluss verpasst
1              89.0               4                                 4
2              82.0               4                                 4
3              70.0               5                                 3
4              78.0               5                                 5
5              14.0               4                                 3
6               6.0               5                                 3
7              90.0               5                                 4
8              15.0               5                                 3
9               2.0               5                                 5

     Ziel (Verpasst) Abfahrt (Verpasst Plan) Abfahrt (Nächste Plan)  \
0                NaN                     NaT    2024-07-08 04:04:00
1        Bad Lausick     2024-07-08 21:56:00    2024-07-08 22:05:00
2        Leipzig Hbf     2024-07-08 21:14:00    2024-07-08 21:18:00
3   Delitzsch unt Bf     2024-07-08 19:27:00    2024-07-08 19:31:00
4  Leipzig-Paunsdorf     2024-07-08 07:15:00    2024-07-08 07:18:00
5            Oschatz     2024-07-08 10:53:00    2024-07-08 10:56:00
6  Erfurt-Bischleben     2024-07-08 22:28:00    2024-07-08 22:31:00
7          Eilenburg     2024-07-08 15:49:00    2024-07-08 15:53:00
8            Oschatz     2024-07-08 07:53:00    2024-07-08 07:56:00
9        Leipzig Hbf     2024-07-08 08:05:00    2024-07-08 08:07:00

   Wartezeit (Min)
0            103.0
1             11.0
2              8.0
3              8.0
4              7.0
5              7.0
6              7.0
7              7.0
8              6.0
9              6.0

In [ ]:
df.drop(
    labels=['id', 'line', 'path', 'eva_nr', 'state', 'zip', 'long', 'lat'], 
    axis=1, 
    inplace=True, 
    errors='ignore')

In [ ]:
df.isna().sum()

In [ ]:
df.info()

In [ ]:
# object zu category umwandeln

#object_cols = df.select_dtypes(include=['object']).columns
#print(object_cols)

#df.info()

In [ ]:
#df.isna().sum()